language: node_js
cache: yarn
node_js:
  - '12.6'

install:
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - pip install --user awscli
  - yarn install

before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

script:
  - yarn test

after_success:
  - openssl aes-256-cbc -K $encrypted_91f35bc24ab1_key -iv $encrypted_91f35bc24ab1_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d

env:
  global:
  - secure: RTPwuTIKsEDrIgca2oC41JeE080VjxJ3y5o5TrbA9J8Ic8zjsGgQPaHUrybHO8wk8zzOthufVNbne3rEDyu9rY0rGp5dzv4ngBOeF+NLn2+uj0rMtlmFJYWWvP3+DyFkLSo3NnLcpAAtXntBlkHUVF2wYYBNdXjEDBLuCHJyE3LZ4AS3x+rE/+pRfLFoEJwkymNmshNxAfHXIhwKIDb8C8lRxy8XxW7Tbq7fryCmAbrt8hhz/Ws25uAw293Tou86pZFWlWI4P5GqTL4k4p3hSuh6e1T0nJjj7m9uyLxwCFp0wk2vKQaTgkD/z1UEsiD5tNN6wSH2TPQI1DnGR5ngMqZSYhbsF/ExrIJm52wW/LVtEY1vUWe8B+S3cnjilua7wNJgk8ejk7ncwOSjSYRFvm43KG+7nRye8v5FJGbfRNVbF6DS71lsOMD0QW6+trCCY/+3b8ScfwkawkBlARv1rqyZIYiANnHqNSqGtcZPCCldgTNCzqPVc5fTzyE4c9iw0nouaDANYXwU4HyvucCeC/dTL3IOGBF7SmVu9TAjK7LNUIAnb3ML2IDCF96IzuNppHVmpZvGZHHbbn29wdDT2NDX9GueLZcPk+SDSoREFC/0XMrN1uEpY8A7djOoFZiNpPcpiLU/ASSlFTRz4xEs1aBjxhE/aQQ1yLBn3lrW+mQ=
  - secure: KZGcTx82rJGNasWjoh+2Ef+MfIPv73xl5hIFsZSxNQnc3RyYYRCozxauuk3LKp4VVeHXpuj37J3+po0Uv/J7sDY6dTR2IfqXN2ebRcu9V7+zBisrJHmLh5tveuETBaLd8/c1JC0SiDl9wtPF8iCk27nQ5J5PxMhNNxs/TGKQSrKlXagbOzsVrB/pxFN+GnTlVuPhjOrVC+YQpgjzSBbaBHqfvIoLY+vRZhiLOE+q+QI1YV2QLmTtrXlEe77K/SUbKbOVDTbPArAWXjb4+CnjUDRSIobfKbp8GlaJgbZ1LgYiz81TZsgiCzaDKPTUfUnGQncZcyVbRYRk/YM1wO4ujOepVBn0nmv4UHKg1S5yXuQNLW6svhv6tox5eyzO3q5nPHzKTs2WmL9PWtC3RH/zsAFowiQ7iw/OD76RiLVgPwXnXIzrS6GnL08Tzpe/SMc/MMCgGDg2ceZAt8luAat6FePdubNvSBMbBGgWkSdzOiYCcc/02t8kzJ40QBOTDuXKQ26bosWsbQeUJqFKuWxQbh9U1L0b4n7VjPoX2uAMbceMjtlZMJ3hfuL2CUoPQYhRgGYeABDMrtHC2Cc42P31OULei3AhIEHrhixlfCZhzpolQolzhOOidRF2gFOhYEaT1aucAB3vD2rO41ePmB88EEyUTYcjq4WrFShjXBJfj1U=