version: 0.2

phases:

  build:
    commands:
      - yarn install
      - yarn test --coverage --maxWorkers 2

  post_build:
    commands:
      - echo REACT_APP_API_ENDPOINT=$API_ENDPOINT >> .env
      - echo REACT_APP_CLIENT_ID=$CLIENT_ID >> .env
      - echo REACT_APP_CLIENT_SECRET=$CLIENT_SECRET >> .env

artifacts:
  files:
    - public/*
    - src/**/*
    - node_modules/**/*
    - package.json
    - yarn.lock
    - .env
