version: 0.2

phases:
  build:
    commands:
      - yarn install
      - yarn test --coverage --maxWorkers 2
      - yarn build
      - cp -rf build/* ./

artifacts:
  files:
    - static/**/*
    - asset-manifest.json
    - favicon.ico
    - index.html
    - manifest.json
    - service-worker.js