export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_SIGN_IN = 'RECEIVE_SIGN_IN';
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP';
export const RECEIVE_AUTH_ERROR = 'RECEIVE_AUTH_ERROR';
export const RECEIVE_PWD = 'RECEIVE_PWD';
export const DISCONNECT = 'DISCONNECT';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const RECEIVE_PROFILE_ERROR = 'RECEIVE_PROFILE_ERROR';

export const REQUEST_ARTWORKS = 'REQUEST_ARTWORKS';
export const RECEIVE_ARTWORKS = 'RECEIVE_ARTWORKS';
export const RECEIVE_ARTWORKS_ERROR = 'RECEIVE_ARTWORKS_ERROR';
export const RECEIVE_ARTWORK = 'RECEIVE_ARTWORK';
export const RECEIVE_ARTWORKCREATE = 'RECEIVE_ARTWORKCREATE';
export const RECEIVE_ADDIMAGE = 'RECEIVE_ADDIMAGE';

export const ADD_BILLING = 'ADD_BILLING';
export const DELETE_BILLING = 'DELETE_BILLING';
export const SET_CURRENT_BILLING = 'SET_CURRENT_BILLING';