export const REQUEST_AUTH = "REQUEST_AUTH";
export const RECEIVE_SIGN_IN = "RECEIVE_SIGN_IN";
export const RECEIVE_SIGN_UP = "RECEIVE_SIGN_UP";
export const RECEIVE_AUTH_ERROR = "RECEIVE_AUTH_ERROR";
export const RECEIVE_PWD = "RECEIVE_PWD";
export const DISCONNECT = "DISCONNECT";

export const REQUEST_PROFILE = "REQUEST_PROFILE";
export const RECEIVE_PROFILE = "RECEIVE_PROFILE";
export const RECEIVE_PROFILE_ERROR = "RECEIVE_PROFILE_ERROR";

export const REQUEST_ARTWORKS = "REQUEST_ARTWORKS";
export const RECEIVE_ARTWORKS = "RECEIVE_ARTWORKS";
export const RECEIVE_ARTWORKS_ERROR = "RECEIVE_ARTWORKS_ERROR";
export const RECEIVE_ARTWORK = "RECEIVE_ARTWORK";
export const RECEIVE_ARTWORKCREATE = "RECEIVE_ARTWORKCREATE";
export const RECEIVE_ADDIMAGE = "RECEIVE_ADDIMAGE";
export const SORT_ARTWORKS = "SORT_ARTWORKS";

export const REQUEST_BILLINGS = "REQUEST_BILLINGS";
export const RECEIVE_BILLINGS = "RECEIVE_BILLINGS";
export const RECEIVE_BILLINGS_ERROR = "RECEIVE_BILLINGS_ERROR";
export const RECEIVE_BILLING = "RECEIVE_BILLING";
export const OPEN_CREATE_BILLING = "OPEN_CREATE_BILLING";
export const SORT_BILLINGS = "SORT_BILLINGS";
export const OPEN_MODIFY_BILLING = "OPEN_MODIFY_BILLING";
export const MODIFY_BILLING = "MODIFY_BILLING";


export const REQUEST_CUSTOMERS = "REQUEST_CUSTOMERS";
export const RECEIVE_CUSTOMERS = "RECEIVE_CUSTOMERS";
export const RECEIVE_CUSTOMERS_ERROR = "RECEIVE_CUSTOMERS_ERROR";
export const RECEIVE_CUSTOMER = "RECEIVE_CUSTOMER";
export const OPEN_CREATE_CUSTOMER = "OPEN_CREATE_CUSTOMER";
export const SORT_CUSTOMERS = "SORT_CUSTOMERS";
export const MODIFY_CUSTOMER = "MODIFY_CUSTOMER";
export const OPEN_MODIFY_CUSTOMER = "OPEN_MODIFY_CUSTOMER";

